---
- name: download, extract and install ngrok zip archive
  unarchive:
    src: "https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip"
    dest: /usr/bin
    mode: 0755
    remote_src: yes
  become: true
- name: create a systemd unit for the ngrok tunnel service
  copy:
    src: ngrok.service
    dest: /etc/systemd/system/ngrok.service
  become: true  
- name: start the ngrok tunnel service
  systemd:
    name: "ngrok"
    state: started
    enabled: yes
  become: true
- name: get address of ngrok 
  shell: cat /var/log/ngrok.log  | egrep -oh "(http://[a-z0-9]+\.ngrok\.io) " | tail -1
  register: ngrok_addr_grep
- name: debug ngrok name 
  debug:
    msg: "{{ngrok_addr_grep.stdout}}"